

# Main. This is where you test the solution class that was generated by calling on it.
# TODO: Call on the solution class and methods and test varied inputs to see if it works.
def main():
    print("Hello World!")


# Solution class. Copy over the information from Leetcode.
# TODO: change the name of the defined method to the problem name
# TODO: Write out the solution for the problem, writing out the class and method
class Solution:
    def something(self):
        return [-1, -1]


# If this is the file that is running "__name__ == __main__",
# run the main() function
if __name__ == "__main__":
    main()
