

# TODO: Call on the solution class and methods and test varied inputs to see if the solution works.

# Main. This is where you test the solution class that was generated by calling on it.
def main():
    print("Hello World!")


# TODO: change the name of the defined method "something" to the problem name
# TODO: Write out the solution for the problem, writing out the class and method
# TODO: ensure the return value and parameters match the problem

# Solution class. Copy over the information from Leetcode.
class Solution:
    def something(self):
        return [-1, -1]


# If this is the file that is running "__name__ == __main__",
# run the main() function
if __name__ == "__main__":
    main()
