// TODO: Change the name of the class to the name of the folder/problem.
// TODO: Maybe? Import Solution.java, etc. for compiling etc.
// TODO: Call on the solution class and methods and test varied inputs to see if the solution works.
// TODO: change the called on method from the solution class

// This file is the equivalent of "main" function in Python.
// Main. This is where you test the solution class that was generated by calling on it.
public class template_main {
    public static void main(String[] args){

        System.out.println("Hello World!");
        Solution solution_obj = new Solution();
        solution_obj.something(null, 0)
    }
}

// Problem description:
