
// This file is the equivalent of "main" function in Python.
// Main. This is where you test the solution class that was generated by calling on it.
public class TwoSum {
    public static void main(String[] args){

        System.out.println("Hello World!");
        Solution solution_obj = new Solution();
        int [] input = {2, 7, 11, 15};
        int target = 9;
        int [] retVal = solution_obj.twoSum(input, target);
        System.out.println(retVal[0]);
        System.out.println(retVal[1]);
    }
}