

# Main. This is where you test the solution class that was generated by calling on it.
def main():
    print("Hello World!")
    solution_obj = Solution
    retVal = solution_obj.twoSum(solution_obj, [2, 7, 11, 15], 9)
    print(retVal)


# Solution class. Copy over the information from Leetcode.
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        returnedVal = []
        for index in range(0, len(nums), 1):
            for secondIndex in range(index+1, len(nums), 1):
                if nums[index] + nums[secondIndex] == target:
                    returnedVal.append(index)
                    returnedVal.append(secondIndex)
                    return returnedVal


# If this is the file that is running "__name__ == __main__",
# run the main() function
if __name__ == "__main__":
    main()
