

# TODO: Call on the solution class and methods and test varied inputs to see if the solution works.

# Main. This is where you test the solution class that was generated by calling on it.
def main():
    print("Hello World!")
    solution_obj = Solution
    input = [7,1,5,3,6,4]
    output = solution_obj.maxProfit(input)
    print(output)

# TODO: Write out the solution for the problem, writing out the class and method

# Solution class. Copy over the information from Leetcode.
class Solution:
    def maxProfit(prices):
        min = 0
        profit = 0

        for i in range(0,len(prices)):
            price = prices[i]
            if (i == 0):
                min = price
            if price < min:
                min = price
            if (price - min > profit):
                profit = price - min

        print(min)
        print(profit)

# If this is the file that is running "__name__ == __main__",
# run the main() function
if __name__ == "__main__":
    main()
