

# TODO: Call on the solution class and methods and test varied inputs to see if the solution works.
# TODO: change the solution call to match the name of the new method.

# Main. This is where you test the solution class that was generated by calling on it.
def main():
    print("Hello World!")
    solution_obj = Solution
    input1 = "anagram"
    input2 = "nagaram"
    output = solution_obj.isAnagram(input1,input2)
    print(output)


# TODO: change the name of the defined method "something" to the problem name
# TODO: Write out the solution for the problem, writing out the class and method
# TODO: ensure the return value and parameters match the problem

# Solution class. Copy over the information from Leetcode.
class Solution:
    def isAnagram(input1, input2):
        if (len(input1) != len(input2)):
            return False
        letterMap = {}
        for char in input1:
            count = 0
            if (letterMap.get(char) == None):
                letterMap[char] = 1
            else:
                letterMap[char] = letterMap[char] + 1

        for char in input2:
            if (letterMap.get(char) == None):
                return False
            else:
                if (letterMap[char] != 0):
                    letterMap[char] = letterMap[char] - 1
                    if (letterMap[char] == 0):
                        letterMap.pop(char)
                else:
                    return False
        return (len(letterMap) == 0)


# If this is the file that is running "__name__ == __main__",
# run the main() function
if __name__ == "__main__":
    main()
